### PR TITLE
Recompute route-idle helper on transition change

### LINKED ISSUE #897: route-idle helper does not recompute when route is no longer idle
The `route-idle` helper is super useful for many use cases of `when-route-idle`. However, I've found that when using the helper in route templates it never recomputes. On initial entry to the route it will work properly, but if the route is re-entered later (e.g. loading a different model), it will immediately return `true`.

This can lead to (IMHO) unexpected behavior, since I would expect the helper to recompute when the route is no longer idle.

### PR DESCRIPTION
**Pull request by nickeidler**
From #897:

> The route-idle helper is super useful for many use cases of when-route-idle. However, I've found that when using the helper in route templates it never recomputes. On initial entry to the route it will work properly, but if the route is re-entered later (e.g. loading a different model), it will immediately return true.
>
> This can lead to (IMHO) unexpected behavior, since I would expect the helper to recompute when the route is no longer idle.

This change proposes fixing the above issue by recomputing the `route-idle` helper on the router service's `routeWillChange` event. See attached videos for comparison of old and new behavior.

Risks:
- The Router service is only available from Ember version >= 3.6.0, so this fix will only work those versions
- This is a potentially breaking change for clients relying on the old behavior of the `route-idle` helper

BEFORE
BEFORE

AFTER
AFTER

Fixes #897 
Closes #898

### CODE REVIEW

File: addon/helpers/route-idle.js [hunk 1]
```diff
@@ -1,17 +1,32 @@
...
   @tracked isIdle = false;
 
+  constructor() {
+    super(...arguments);
+
+    this.router.on('routeWillChange', () => {
+      if (!this.isDestroying) {
+        this.isIdle = false;
+      }
+    });
```
Comment (rwjblue) [inline addon/helpers/route-idle.js:18]: Hmm, I think this may have issues when there are many `route-idle` invocations on a site at once. It also (currently) never tears down so we end up with many subscriptions queued up over time.

File: addon/helpers/route-idle.js [hunk 2]
```diff
@@ -1,17 +1,32 @@
...
     if (this.isIdle) {
       return true;
     }
 
     whenRouteIdle().then(() => {
-      this.isIdle = true;
+      if (!this.isDestroying) {
+        this.isIdle = true;
+      }
     });
```
Comment (rwjblue) [inline addon/helpers/route-idle.js:30]: Instead of manually subscribing, we should be able to leverage auto-tracking for this. See https://github.com/rwjblue/ember-router-helpers/pull/263 for how I've done it in the past.

File: package.json [hunk 3]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "ember-app-scheduler",
-  "version": "5.1.0",
+  "version": "6.0.0",
```
Comment (rwjblue) [inline package.json:3]: Please revert this part of the update. We generally like to bump the version as part of the release process itself.

File: addon/helpers/route-idle.js (hunk 2 above)
Comment (nickeidler) [reply addon/helpers/route-idle.js]: Thanks for calling that out! I'm still getting the hang of auto-tracking as a paradigm-- refactored to make this component much more elegant.

File: addon/helpers/route-idle.js (hunk 1 above)
Comment (nickeidler) [reply addon/helpers/route-idle.js]: Refactored to use auto-tracking. Source of truth `isIdle` Boolean is now managed in the same place as the core `route-idle` logic in `scheduler.ts`, so multiple invocations / subscription cleanup should no longer be an issue.

File: addon/scheduler.ts [hunk 4]
```diff
@@ -27,6 +28,12 @@ const waiter = buildWaiter('ember-app-scheduler-waiter');
 
 reset();
 
+class Scheduler {
+  @tracked isIdle = false;
+}
+const scheduler = new Scheduler();
+export default scheduler;
```
Comment (nickeidler) [inline addon/scheduler.ts:35]: Only reason I'm creating a class here is to setup auto-tracking on `isIdle`. Not sure if there is a more elegant way to do this in a functional module.

Comment (rwjblue) [reply addon/scheduler.ts:35]: Nope, this is perfectly fine!

**Review by rwjblue — APPROVED** [review]
Awesome, this looks great to me thanks for working on it!

@scalvert - Seem ok to you?

File: addon/scheduler.ts (hunk 4 above)
Comment (scalvert) [reply addon/scheduler.ts:35]: I think having this class is totally fine. I wouldn't put it here though. I'd put it in the helper file itself though, not here. It feels odd here.

**Review by scalvert — CHANGES_REQUESTED** [review]

File: addon/scheduler.ts (hunk 4 above)
Comment (scalvert) [reply addon/scheduler.ts:35]: Actually ignore this. We need this here since we need to set `scheduler.isIdle`.

**Comment by scalvert** [comment]
Thanks for working on this, @nickeidler!

**Review by scalvert — APPROVED** [review]
